export const CITY_UPDATED = 'CITY_UPDATED';
export const CITY_TOGGLE_TO_FAV = 'CITY_TOGGLE_TO_FAV';
export const TEMPERATURE_TYPE_IMP = 'TEMPERATURE_TYPE_IMP';
export const TEMPERATURE_TYPE_METR = 'TEMPERATURE_TYPE_METR';
export const FETCH_WEATHER_LIST_SUCCESS = 'FETCH_WEATHER_LIST_SUCCESS';
export const FETCH_WEATHER_LIST_REQUEST = 'FETCH_WEATHER_LIST_REQUEST';
export const FETCH_WEATHER_LIST_FAILURE = 'FETCH_WEATHER_LIST_FAILURE';